### ISSUE TITLE
Add support for using binary diff on update

### ISSUE THREAD

**Issue by jhaynie** [pinpt/agent#28]
- Generate a bsdiff patch file on release (and upload to github as part of release)
- Add support for update which uses bsdiff (if possible) when upgrading from one to the next release (for skipping releases, just do a full install)

Investigate using the bzip2 writer from  https://github.com/dsnet/compress/tree/master/bzip2 and using https://github.com/kr/binarydist but replacing the writer which uses command line at https://github.com/kr/binarydist/blob/main/bzip2.go#L26

**Comment by xzandrew** [comment]
Moved issue to internal jira
